export const PERMISSIONS = {
  IDENTITY_PROFILE_READ_SELF: 'identity.profile.read.self',
  IDENTITY_PROFILE_UPDATE_SELF: 'identity.profile.update.self',
  IDENTITY_PROVIDER_PROFILE_MANAGE_SELF: 'identity.provider-profile.manage.self',
  IDENTITY_PROVIDER_PROFILE_READ_SELF: 'identity.provider-profile.read.self',
  IDENTITY_PROVIDER_PROFILE_UPDATE_SELF: 'identity.provider-profile.update.self',
  IDENTITY_PROVIDER_PORTFOLIO_MANAGE_SELF: 'identity.provider-portfolio.manage.self',
  IDENTITY_PROVIDER_CERTIFICATION_MANAGE_SELF: 'identity.provider-certification.manage.self',
  IDENTITY_PROVIDER_AVAILABILITY_UPDATE_SELF: 'identity.provider-availability.update.self',
  IDENTITY_PROVIDER_ONBOARDING_SELF: 'identity.provider-onboarding.self',
  IDENTITY_PROVIDER_VERIFICATION_READ_SELF: 'identity.provider-verification.read.self',
  IDENTITY_PROVIDER_VERIFICATION_SUBMIT_SELF: 'identity.provider-verification.submit.self',
  IDENTITY_PAYOUT_METHOD_MANAGE_SELF: 'identity.payout-method.manage.self',
  IDENTITY_PAYOUT_METHOD_READ_SELF: 'identity.payout-method.read.self',
  IDENTITY_PAYOUT_METHOD_CREATE_SELF: 'identity.payout-method.create.self',
  IDENTITY_PAYOUT_METHOD_UPDATE_SELF: 'identity.payout-method.update.self',
  IDENTITY_PAYOUT_METHOD_DELETE_SELF: 'identity.payout-method.delete.self',
  IDENTITY_PAYOUT_METHOD_SET_DEFAULT_SELF: 'identity.payout-method.set-default.self',
  IDENTITY_PREFERENCES_MANAGE_SELF: 'identity.preferences.manage.self',
  IDENTITY_PREFERENCES_READ_SELF: 'identity.preferences.read.self',
  IDENTITY_PREFERENCES_UPDATE_SELF: 'identity.preferences.update.self',
  IDENTITY_PREFERENCES_UPDATE_NOTIFICATIONS_SELF: 'identity.preferences.update-notifications.self',
  IDENTITY_PREFERENCES_UPDATE_PRIVACY_SELF: 'identity.preferences.update-privacy.self',
  IDENTITY_FOLLOW_MANAGE: 'identity.follow.manage',
  IDENTITY_FOLLOW_CREATE_SELF: 'identity.follow.create.self',
  IDENTITY_FOLLOW_DELETE_SELF: 'identity.follow.delete.self',
  IDENTITY_FOLLOW_READ_SELF: 'identity.follow.read.self',
  IDENTITY_USER_SEARCH_MANAGE: 'identity.user-search.manage',
  IDENTITY_USER_SEARCH_CREATE_SELF: 'identity.user-search.create.self',
  IDENTITY_USER_SEARCH_READ_SELF: 'identity.user-search.read.self',
  IDENTITY_USER_SEARCH_DELETE_SELF: 'identity.user-search.delete.self',

  MARKETPLACE_SERVICE_READ_OWN: 'marketplace.service.read.own',
  MARKETPLACE_SERVICE_CREATE_OWN: 'marketplace.service.create.own',
  MARKETPLACE_SERVICE_UPDATE_OWN: 'marketplace.service.update.own',
  MARKETPLACE_SERVICE_PUBLISH_OWN: 'marketplace.service.publish.own',
  MARKETPLACE_SERVICE_PAUSE_OWN: 'marketplace.service.pause.own',
  MARKETPLACE_SERVICE_DELETE_OWN: 'marketplace.service.delete.own',
  MARKETPLACE_SERVICE_IMAGE_ADD_OWN: 'marketplace.service.image.add.own',
  MARKETPLACE_SERVICE_IMAGE_DELETE_OWN: 'marketplace.service.image.delete.own',
  MARKETPLACE_REVIEW_MANAGE: 'marketplace.review.manage',
  MARKETPLACE_REVIEW_CREATE: 'marketplace.review.create',
  MARKETPLACE_REVIEW_UPDATE_OWN: 'marketplace.review.update.own',
  MARKETPLACE_REVIEW_DELETE_OWN: 'marketplace.review.delete.own',
  MARKETPLACE_REVIEW_RESPOND_PROVIDER: 'marketplace.review.respond.provider',
  MARKETPLACE_REVIEW_MARK_HELPFUL: 'marketplace.review.mark-helpful',
  MARKETPLACE_BOOKING_CUSTOMER: 'marketplace.booking.customer',
  MARKETPLACE_BOOKING_PROVIDER: 'marketplace.booking.provider',
  MARKETPLACE_BOOKING_PARTICIPANT: 'marketplace.booking.participant',
  MARKETPLACE_BOOKING_CUSTOMER_READ_OWN: 'marketplace.booking.customer.read.own',
  MARKETPLACE_BOOKING_CUSTOMER_CREATE: 'marketplace.booking.customer.create',
  MARKETPLACE_BOOKING_CUSTOMER_APPROVE: 'marketplace.booking.customer.approve',
  MARKETPLACE_BOOKING_CUSTOMER_REQUEST_CORRECTION: 'marketplace.booking.customer.request-correction',
  MARKETPLACE_BOOKING_CUSTOMER_PAY: 'marketplace.booking.customer.pay',
  MARKETPLACE_BOOKING_CUSTOMER_COMPLETE: 'marketplace.booking.customer.complete',
  MARKETPLACE_BOOKING_PROVIDER_READ_OWN: 'marketplace.booking.provider.read.own',
  MARKETPLACE_BOOKING_PROVIDER_CONFIRM: 'marketplace.booking.provider.confirm',
  MARKETPLACE_BOOKING_PROVIDER_START: 'marketplace.booking.provider.start',
  MARKETPLACE_BOOKING_PROVIDER_COMPLETE: 'marketplace.booking.provider.complete',
  MARKETPLACE_BOOKING_PROVIDER_DELIVER: 'marketplace.booking.provider.deliver',
  MARKETPLACE_BOOKING_PROVIDER_PAY_COMMISSION: 'marketplace.booking.provider.pay-commission',
  MARKETPLACE_BOOKING_PARTICIPANT_READ: 'marketplace.booking.participant.read',
  MARKETPLACE_BOOKING_PARTICIPANT_UPDATE: 'marketplace.booking.participant.update',
  MARKETPLACE_BOOKING_PARTICIPANT_CANCEL: 'marketplace.booking.participant.cancel',
  MARKETPLACE_BOOKING_PARTICIPANT_VERIFY_PAYMENT: 'marketplace.booking.participant.verify-payment',
  MARKETPLACE_BOOKING_FILE_MANAGE_PARTICIPANT: 'marketplace.booking.file.manage.participant',
  MARKETPLACE_BOOKING_CHAT_MANAGE_PARTICIPANT: 'marketplace.booking.chat.manage.participant',
  MARKETPLACE_CONTRACT_MANAGE_OWN: 'marketplace.contract.manage.own',
  MARKETPLACE_CONTRACT_CREATE_OWN: 'marketplace.contract.create.own',
  MARKETPLACE_CONTRACT_READ_OWN: 'marketplace.contract.read.own',
  MARKETPLACE_CONTRACT_UPDATE_OWN: 'marketplace.contract.update.own',
  MARKETPLACE_CONTRACT_MILESTONE_MANAGE_OWN: 'marketplace.contract.milestone.manage.own',
  MARKETPLACE_CONTRACT_FILE_UPLOAD_OWN: 'marketplace.contract.file-upload.own',
  MARKETPLACE_CONTRACT_ACTIVITY_READ_OWN: 'marketplace.contract.activity.read.own',
  MARKETPLACE_GIG_MANAGE: 'marketplace.gig.manage',
  MARKETPLACE_GIG_CREATE_OWN: 'marketplace.gig.create.own',
  MARKETPLACE_GIG_READ: 'marketplace.gig.read',
  MARKETPLACE_GIG_UPDATE_OWN: 'marketplace.gig.update.own',
  MARKETPLACE_GIG_DELETE_OWN: 'marketplace.gig.delete.own',
  MARKETPLACE_PROPOSAL_MANAGE: 'marketplace.proposal.manage',
  MARKETPLACE_PROPOSAL_CREATE_OWN: 'marketplace.proposal.create.own',
  MARKETPLACE_PROPOSAL_READ_OWN: 'marketplace.proposal.read.own',
  MARKETPLACE_DISCOVERY_PERSONALIZED_READ: 'marketplace.discovery.personalized.read',

  COMMUNITY_POST_MANAGE: 'community.post.manage',
  COMMUNITY_POST_READ: 'community.post.read',
  COMMUNITY_POST_CREATE: 'community.post.create',
  COMMUNITY_POST_UPDATE_OWN: 'community.post.update.own',
  COMMUNITY_POST_DELETE_OWN: 'community.post.delete.own',
  COMMUNITY_POST_INTERACT: 'community.post.interact',
  COMMUNITY_COMMENT_MANAGE: 'community.comment.manage',
  COMMUNITY_COMMENT_READ: 'community.comment.read',
  COMMUNITY_COMMENT_CREATE: 'community.comment.create',
  COMMUNITY_COMMENT_UPDATE_OWN: 'community.comment.update.own',
  COMMUNITY_COMMENT_DELETE_OWN: 'community.comment.delete.own',
  COMMUNITY_COMMENT_INTERACT: 'community.comment.interact',
  COMMUNITY_SHARE_MANAGE: 'community.share.manage',
  COMMUNITY_SHARE_READ: 'community.share.read',
  COMMUNITY_SHARE_CREATE: 'community.share.create',
  COMMUNITY_SHARE_DELETE_OWN: 'community.share.delete.own',
  COMMUNITY_MESSAGE_MANAGE: 'community.message.manage',
  COMMUNITY_MESSAGE_READ_OWN: 'community.message.read.own',
  COMMUNITY_MESSAGE_SEND_OWN: 'community.message.send.own',
  COMMUNITY_MESSAGE_UPDATE_OWN: 'community.message.update.own',
  COMMUNITY_MESSAGE_DELETE_OWN: 'community.message.delete.own',
  COMMUNITY_CONVERSATION_MANAGE: 'community.conversation.manage',
  COMMUNITY_CONVERSATION_READ_OWN: 'community.conversation.read.own',
  COMMUNITY_CONVERSATION_CREATE_OWN: 'community.conversation.create.own',
  COMMUNITY_CONVERSATION_UPDATE_OWN: 'community.conversation.update.own',
  COMMUNITY_CONVERSATION_DELETE_OWN: 'community.conversation.delete.own',
  COMMUNITY_CONVERSATION_PARTICIPANT_MANAGE: 'community.conversation.participant.manage',
  COMMUNITY_AD_MANAGE: 'community.ad.manage',
  COMMUNITY_AD_READ_FEED: 'community.ad.read.feed',
  COMMUNITY_AD_MANAGE_OWN: 'community.ad.manage.own',
  COMMUNITY_AD_INTERACT: 'community.ad.interact',
  COMMUNITY_PUSH_SELF: 'community.push.self',
  COMMUNITY_PUSH_BROADCAST: 'community.push.broadcast',

  BILLING_PAYMENT_MANAGE_SELF: 'billing.payment.manage.self',
  BILLING_PAYMENT_INITIALIZE_SELF: 'billing.payment.initialize.self',
  BILLING_PAYMENT_VERIFY_SELF: 'billing.payment.verify.self',
  BILLING_PAYMENT_READ_HISTORY_SELF: 'billing.payment.read-history.self',
  BILLING_PAYMENT_READ_DETAIL_SELF: 'billing.payment.read-detail.self',
  BILLING_PAYOUT_BANK_VERIFY_SELF: 'billing.payout.bank.verify.self',
  BILLING_PAYOUT_BALANCE_READ_SELF: 'billing.payout.balance.read.self',
  BILLING_PAYOUT_HISTORY_READ_SELF: 'billing.payout.history.read.self',
  BILLING_PAYOUT_DETAIL_READ_SELF: 'billing.payout.detail.read.self',
  BILLING_PAYOUT_CREATE_SELF: 'billing.payout.create.self',
  BILLING_PAYOUT_CANCEL_SELF: 'billing.payout.cancel.self',
  BILLING_PAYOUT_RELEASE_READ_SELF: 'billing.payout.release.read.self',
  BILLING_PAYOUT_PROCESS_ADMIN: 'billing.payout.process.admin',
  BILLING_PAYOUT_RELEASE_READ_ADMIN: 'billing.payout.release.read.admin',
  BILLING_PAYOUT_RELEASE_CREATE_ADMIN: 'billing.payout.release.create.admin',
  BILLING_SUBSCRIPTION_MANAGE_SELF: 'billing.subscription.manage.self',
  BILLING_SUBSCRIPTION_READ_SELF: 'billing.subscription.read.self',
  BILLING_SUBSCRIPTION_CREATE_SELF: 'billing.subscription.create.self',
  BILLING_SUBSCRIPTION_CANCEL_SELF: 'billing.subscription.cancel.self',
  BILLING_PLAN_READ: 'billing.plan.read',
  BILLING_PLAN_MANAGE: 'billing.plan.manage',

  OPS_ANALYTICS_SELF: 'ops.analytics.self',
  OPS_ADMIN_OVERVIEW_READ: 'ops.admin.overview.read',
  OPS_ADMIN_MAINTENANCE_RECOUNT: 'ops.admin.maintenance.recount',
  OPS_ADMIN_DASHBOARD_STATS_READ: 'ops.admin.dashboard-stats.read',
  OPS_ADMIN_BOOKING_LIST_READ: 'ops.admin.booking-list.read',
  OPS_ADMIN_BOOKING_DETAIL_READ: 'ops.admin.booking-detail.read',
  OPS_ADMIN_BOOKING_STATUS_UPDATE: 'ops.admin.booking-status.update',
  OPS_ADMIN_BOOKING_FORCE_REFUND: 'ops.admin.booking.force-refund',
  OPS_ADMIN_PAYMENT_LIST_READ: 'ops.admin.payment-list.read',
  OPS_ADMIN_PAYMENT_SUMMARY_READ: 'ops.admin.payment-summary.read',
  OPS_ADMIN_DISPUTE_LIST_READ: 'ops.admin.dispute-list.read',
  OPS_ADMIN_DISPUTE_DETAIL_READ: 'ops.admin.dispute-detail.read',
  OPS_ADMIN_DISPUTE_RESOLVE: 'ops.admin.dispute.resolve',
  OPS_ADMIN_SERVICE_MODERATE: 'ops.admin.service.moderate',
  OPS_ADMIN_CONTENT_DELETE: 'ops.admin.content.delete',
  OPS_REPORTING_AUDIT_LOG_READ: 'ops.reporting.audit-log.read',
  OPS_REPORTING_USER_GROWTH_READ: 'ops.reporting.user-growth.read',
  OPS_REPORTING_REVENUE_READ: 'ops.reporting.revenue.read',
  OPS_REPORTING_SERVICE_PERFORMANCE_READ: 'ops.reporting.service-performance.read',
  OPS_REPORTING_CSV_EXPORT: 'ops.reporting.csv.export',
  OPS_USER_MANAGEMENT_READ: 'ops.user-management.read',
  OPS_USER_MANAGEMENT_UPDATE: 'ops.user-management.update',
  OPS_USER_STATUS_MANAGE: 'ops.user-status.manage',
  OPS_USER_VERIFICATION_QUEUE_READ: 'ops.user-verification-queue.read',
  OPS_USER_VERIFICATION_REVIEW: 'ops.user-verification.review',
  OPS_USER_STRIKE_MANAGE: 'ops.user-strike.manage',
  OPS_USER_FEATURED_MANAGE: 'ops.user-featured.manage',
  OPS_MODERATION_REPORT_CREATE: 'ops.moderation.report.create',
  OPS_MODERATION_REPORT_READ: 'ops.moderation.report.read',
  OPS_MODERATION_REPORT_RESOLVE: 'ops.moderation.report.resolve',
  OPS_PERMISSION_MATRIX_READ: 'ops.permission-matrix.read',
  OPS_PERMISSION_MATRIX_WRITE: 'ops.permission-matrix.write',
  OPS_USER_ROLE_READ: 'ops.user-role.read',
  OPS_USER_ROLE_ASSIGN: 'ops.user-role.assign',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export type PermissionDefinition = {
  key: PermissionKey;
  label: string;
  domain: string;
  description: string;
};

export const PERMISSION_DEFINITIONS: PermissionDefinition[] = [
  { key: PERMISSIONS.IDENTITY_PROFILE_READ_SELF, label: 'Read Own Profile', domain: 'identity', description: 'Read own profile details' },
  { key: PERMISSIONS.IDENTITY_PROFILE_UPDATE_SELF, label: 'Update Own Profile', domain: 'identity', description: 'Update own profile details' },
  { key: PERMISSIONS.IDENTITY_PROVIDER_PROFILE_MANAGE_SELF, label: 'Manage Provider Profile', domain: 'identity', description: 'Create and manage own provider profile' },
  { key: PERMISSIONS.IDENTITY_PROVIDER_PROFILE_READ_SELF, label: 'Read Provider Profile', domain: 'identity', description: 'Read own provider profile' },
  { key: PERMISSIONS.IDENTITY_PROVIDER_PROFILE_UPDATE_SELF, label: 'Update Provider Profile', domain: 'identity', description: 'Update own provider profile' },
  { key: PERMISSIONS.IDENTITY_PROVIDER_PORTFOLIO_MANAGE_SELF, label: 'Manage Provider Portfolio', domain: 'identity', description: 'Manage own provider portfolio items' },
  { key: PERMISSIONS.IDENTITY_PROVIDER_CERTIFICATION_MANAGE_SELF, label: 'Manage Provider Certifications', domain: 'identity', description: 'Manage own provider certifications' },
  { key: PERMISSIONS.IDENTITY_PROVIDER_AVAILABILITY_UPDATE_SELF, label: 'Update Provider Availability', domain: 'identity', description: 'Update own provider availability' },
  { key: PERMISSIONS.IDENTITY_PROVIDER_ONBOARDING_SELF, label: 'Provider Onboarding', domain: 'identity', description: 'Run provider payout onboarding flow' },
  { key: PERMISSIONS.IDENTITY_PROVIDER_VERIFICATION_READ_SELF, label: 'Read Provider Verification', domain: 'identity', description: 'Read own provider verification status/history' },
  { key: PERMISSIONS.IDENTITY_PROVIDER_VERIFICATION_SUBMIT_SELF, label: 'Submit Provider Verification', domain: 'identity', description: 'Submit own provider verification request' },
  { key: PERMISSIONS.IDENTITY_PAYOUT_METHOD_MANAGE_SELF, label: 'Manage Payout Methods', domain: 'identity', description: 'Manage own payout methods' },
  { key: PERMISSIONS.IDENTITY_PAYOUT_METHOD_READ_SELF, label: 'Read Payout Methods', domain: 'identity', description: 'Read own payout methods' },
  { key: PERMISSIONS.IDENTITY_PAYOUT_METHOD_CREATE_SELF, label: 'Create Payout Method', domain: 'identity', description: 'Create own payout method' },
  { key: PERMISSIONS.IDENTITY_PAYOUT_METHOD_UPDATE_SELF, label: 'Update Payout Method', domain: 'identity', description: 'Update own payout method' },
  { key: PERMISSIONS.IDENTITY_PAYOUT_METHOD_DELETE_SELF, label: 'Delete Payout Method', domain: 'identity', description: 'Delete own payout method' },
  { key: PERMISSIONS.IDENTITY_PAYOUT_METHOD_SET_DEFAULT_SELF, label: 'Set Default Payout Method', domain: 'identity', description: 'Set default payout method for own account' },
  { key: PERMISSIONS.IDENTITY_PREFERENCES_MANAGE_SELF, label: 'Manage Preferences', domain: 'identity', description: 'Manage own app preferences' },
  { key: PERMISSIONS.IDENTITY_PREFERENCES_READ_SELF, label: 'Read Preferences', domain: 'identity', description: 'Read own app preferences' },
  { key: PERMISSIONS.IDENTITY_PREFERENCES_UPDATE_SELF, label: 'Update Preferences', domain: 'identity', description: 'Update own app preferences' },
  { key: PERMISSIONS.IDENTITY_PREFERENCES_UPDATE_NOTIFICATIONS_SELF, label: 'Update Notification Preferences', domain: 'identity', description: 'Update own notification settings' },
  { key: PERMISSIONS.IDENTITY_PREFERENCES_UPDATE_PRIVACY_SELF, label: 'Update Privacy Preferences', domain: 'identity', description: 'Update own privacy settings' },
  { key: PERMISSIONS.IDENTITY_FOLLOW_MANAGE, label: 'Manage Follows', domain: 'identity', description: 'Follow and unfollow users' },
  { key: PERMISSIONS.IDENTITY_FOLLOW_CREATE_SELF, label: 'Follow Users', domain: 'identity', description: 'Follow users from own account' },
  { key: PERMISSIONS.IDENTITY_FOLLOW_DELETE_SELF, label: 'Unfollow Users', domain: 'identity', description: 'Unfollow users from own account' },
  { key: PERMISSIONS.IDENTITY_FOLLOW_READ_SELF, label: 'Read Follow Graph', domain: 'identity', description: 'Read own and target follow relationships' },
  { key: PERMISSIONS.IDENTITY_USER_SEARCH_MANAGE, label: 'Manage Search History', domain: 'identity', description: 'Save and manage own search history' },
  { key: PERMISSIONS.IDENTITY_USER_SEARCH_CREATE_SELF, label: 'Create Search History', domain: 'identity', description: 'Save own search history item' },
  { key: PERMISSIONS.IDENTITY_USER_SEARCH_READ_SELF, label: 'Read Search History', domain: 'identity', description: 'Read own search history' },
  { key: PERMISSIONS.IDENTITY_USER_SEARCH_DELETE_SELF, label: 'Delete Search History', domain: 'identity', description: 'Delete own search history item' },

  { key: PERMISSIONS.MARKETPLACE_SERVICE_READ_OWN, label: 'Read Own Services', domain: 'marketplace', description: 'Read own service listings' },
  { key: PERMISSIONS.MARKETPLACE_SERVICE_CREATE_OWN, label: 'Create Own Services', domain: 'marketplace', description: 'Create own service listings' },
  { key: PERMISSIONS.MARKETPLACE_SERVICE_UPDATE_OWN, label: 'Update Own Services', domain: 'marketplace', description: 'Update own service listings' },
  { key: PERMISSIONS.MARKETPLACE_SERVICE_PUBLISH_OWN, label: 'Publish Own Services', domain: 'marketplace', description: 'Publish own service listings' },
  { key: PERMISSIONS.MARKETPLACE_SERVICE_PAUSE_OWN, label: 'Pause Own Services', domain: 'marketplace', description: 'Pause own service listings' },
  { key: PERMISSIONS.MARKETPLACE_SERVICE_DELETE_OWN, label: 'Delete Own Services', domain: 'marketplace', description: 'Delete own service listings' },
  { key: PERMISSIONS.MARKETPLACE_SERVICE_IMAGE_ADD_OWN, label: 'Add Service Images', domain: 'marketplace', description: 'Add images to own service listings' },
  { key: PERMISSIONS.MARKETPLACE_SERVICE_IMAGE_DELETE_OWN, label: 'Delete Service Images', domain: 'marketplace', description: 'Remove images from own service listings' },
  { key: PERMISSIONS.MARKETPLACE_REVIEW_MANAGE, label: 'Manage Reviews', domain: 'marketplace', description: 'Create and manage reviews and responses' },
  { key: PERMISSIONS.MARKETPLACE_REVIEW_CREATE, label: 'Create Reviews', domain: 'marketplace', description: 'Create reviews for completed bookings' },
  { key: PERMISSIONS.MARKETPLACE_REVIEW_UPDATE_OWN, label: 'Update Own Reviews', domain: 'marketplace', description: 'Update own submitted reviews' },
  { key: PERMISSIONS.MARKETPLACE_REVIEW_DELETE_OWN, label: 'Delete Own Reviews', domain: 'marketplace', description: 'Delete own submitted reviews' },
  { key: PERMISSIONS.MARKETPLACE_REVIEW_RESPOND_PROVIDER, label: 'Respond to Reviews', domain: 'marketplace', description: 'Respond to reviews as provider' },
  { key: PERMISSIONS.MARKETPLACE_REVIEW_MARK_HELPFUL, label: 'Mark Review Helpful', domain: 'marketplace', description: 'Mark reviews as helpful' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_CUSTOMER, label: 'Customer Booking Actions', domain: 'marketplace', description: 'Create and manage bookings as customer' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PROVIDER, label: 'Provider Booking Actions', domain: 'marketplace', description: 'Manage bookings as provider' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PARTICIPANT, label: 'Booking Participant Access', domain: 'marketplace', description: 'Access booking resources as participant' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_CUSTOMER_READ_OWN, label: 'Read Customer Bookings', domain: 'marketplace', description: 'Read own customer bookings' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_CUSTOMER_CREATE, label: 'Create Booking', domain: 'marketplace', description: 'Create booking as customer' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_CUSTOMER_APPROVE, label: 'Approve Delivery', domain: 'marketplace', description: 'Approve booking delivery as customer' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_CUSTOMER_REQUEST_CORRECTION, label: 'Request Correction', domain: 'marketplace', description: 'Request correction on delivered booking' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_CUSTOMER_PAY, label: 'Pay Booking', domain: 'marketplace', description: 'Pay booking related checkout/payment requests as customer' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_CUSTOMER_COMPLETE, label: 'Complete Booking as Customer', domain: 'marketplace', description: 'Mark order/booking complete as customer' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PROVIDER_READ_OWN, label: 'Read Provider Bookings', domain: 'marketplace', description: 'Read own provider bookings' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PROVIDER_CONFIRM, label: 'Confirm Booking', domain: 'marketplace', description: 'Confirm booking as provider' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PROVIDER_START, label: 'Start Booking Work', domain: 'marketplace', description: 'Start booking work as provider' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PROVIDER_COMPLETE, label: 'Complete Booking as Provider', domain: 'marketplace', description: 'Complete booking flow as provider' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PROVIDER_DELIVER, label: 'Deliver Booking Work', domain: 'marketplace', description: 'Deliver booking output as provider' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PROVIDER_PAY_COMMISSION, label: 'Pay Booking Commission', domain: 'marketplace', description: 'Pay platform commission as provider' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PARTICIPANT_READ, label: 'Read Booking Detail', domain: 'marketplace', description: 'Read booking detail as participant' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PARTICIPANT_UPDATE, label: 'Update Booking', domain: 'marketplace', description: 'Update booking as participant' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PARTICIPANT_CANCEL, label: 'Cancel Booking', domain: 'marketplace', description: 'Cancel booking as participant' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_PARTICIPANT_VERIFY_PAYMENT, label: 'Verify Booking Payment', domain: 'marketplace', description: 'Verify booking payment as participant' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_FILE_MANAGE_PARTICIPANT, label: 'Manage Booking Files', domain: 'marketplace', description: 'Manage booking workspace files as participant' },
  { key: PERMISSIONS.MARKETPLACE_BOOKING_CHAT_MANAGE_PARTICIPANT, label: 'Manage Booking Chat', domain: 'marketplace', description: 'Manage booking workspace chat as participant' },
  { key: PERMISSIONS.MARKETPLACE_CONTRACT_MANAGE_OWN, label: 'Manage Own Contracts', domain: 'marketplace', description: 'Create and manage own contracts' },
  { key: PERMISSIONS.MARKETPLACE_CONTRACT_CREATE_OWN, label: 'Create Contract', domain: 'marketplace', description: 'Create own contracts' },
  { key: PERMISSIONS.MARKETPLACE_CONTRACT_READ_OWN, label: 'Read Contracts', domain: 'marketplace', description: 'Read own contracts' },
  { key: PERMISSIONS.MARKETPLACE_CONTRACT_UPDATE_OWN, label: 'Update Contract', domain: 'marketplace', description: 'Update own contracts' },
  { key: PERMISSIONS.MARKETPLACE_CONTRACT_MILESTONE_MANAGE_OWN, label: 'Manage Contract Milestones', domain: 'marketplace', description: 'Manage milestones for own contracts' },
  { key: PERMISSIONS.MARKETPLACE_CONTRACT_FILE_UPLOAD_OWN, label: 'Upload Contract Files', domain: 'marketplace', description: 'Upload files to own contracts' },
  { key: PERMISSIONS.MARKETPLACE_CONTRACT_ACTIVITY_READ_OWN, label: 'Read Contract Activity', domain: 'marketplace', description: 'Read activity log for own contracts' },
  { key: PERMISSIONS.MARKETPLACE_GIG_MANAGE, label: 'Manage Gigs', domain: 'marketplace', description: 'Create and manage gigs' },
  { key: PERMISSIONS.MARKETPLACE_GIG_CREATE_OWN, label: 'Create Gig', domain: 'marketplace', description: 'Create own gigs' },
  { key: PERMISSIONS.MARKETPLACE_GIG_READ, label: 'Read Gigs', domain: 'marketplace', description: 'Read gig listings/details' },
  { key: PERMISSIONS.MARKETPLACE_GIG_UPDATE_OWN, label: 'Update Gig', domain: 'marketplace', description: 'Update own gigs' },
  { key: PERMISSIONS.MARKETPLACE_GIG_DELETE_OWN, label: 'Delete Gig', domain: 'marketplace', description: 'Delete own gigs' },
  { key: PERMISSIONS.MARKETPLACE_PROPOSAL_MANAGE, label: 'Manage Proposals', domain: 'marketplace', description: 'Submit and read own proposals' },
  { key: PERMISSIONS.MARKETPLACE_PROPOSAL_CREATE_OWN, label: 'Create Proposal', domain: 'marketplace', description: 'Create own proposals' },
  { key: PERMISSIONS.MARKETPLACE_PROPOSAL_READ_OWN, label: 'Read Proposals', domain: 'marketplace', description: 'Read own proposals' },
  { key: PERMISSIONS.MARKETPLACE_DISCOVERY_PERSONALIZED_READ, label: 'Read Personalized Discovery', domain: 'marketplace', description: 'Read personalized recommendations' },

  { key: PERMISSIONS.COMMUNITY_POST_MANAGE, label: 'Manage Posts', domain: 'community', description: 'Create and manage social posts' },
  { key: PERMISSIONS.COMMUNITY_POST_READ, label: 'Read Posts', domain: 'community', description: 'Read social post content' },
  { key: PERMISSIONS.COMMUNITY_POST_CREATE, label: 'Create Posts', domain: 'community', description: 'Create social posts' },
  { key: PERMISSIONS.COMMUNITY_POST_UPDATE_OWN, label: 'Update Own Posts', domain: 'community', description: 'Update own social posts' },
  { key: PERMISSIONS.COMMUNITY_POST_DELETE_OWN, label: 'Delete Own Posts', domain: 'community', description: 'Delete own social posts' },
  { key: PERMISSIONS.COMMUNITY_POST_INTERACT, label: 'Interact with Posts', domain: 'community', description: 'Like/unlike posts' },
  { key: PERMISSIONS.COMMUNITY_COMMENT_MANAGE, label: 'Manage Comments', domain: 'community', description: 'Create and manage comments' },
  { key: PERMISSIONS.COMMUNITY_COMMENT_READ, label: 'Read Comments', domain: 'community', description: 'Read comment threads' },
  { key: PERMISSIONS.COMMUNITY_COMMENT_CREATE, label: 'Create Comments', domain: 'community', description: 'Create/reply to comments' },
  { key: PERMISSIONS.COMMUNITY_COMMENT_UPDATE_OWN, label: 'Update Own Comments', domain: 'community', description: 'Update own comments' },
  { key: PERMISSIONS.COMMUNITY_COMMENT_DELETE_OWN, label: 'Delete Own Comments', domain: 'community', description: 'Delete own comments' },
  { key: PERMISSIONS.COMMUNITY_COMMENT_INTERACT, label: 'Interact with Comments', domain: 'community', description: 'Like/unlike comments' },
  { key: PERMISSIONS.COMMUNITY_SHARE_MANAGE, label: 'Manage Shares', domain: 'community', description: 'Create and manage shares' },
  { key: PERMISSIONS.COMMUNITY_SHARE_READ, label: 'Read Shares', domain: 'community', description: 'Read share records' },
  { key: PERMISSIONS.COMMUNITY_SHARE_CREATE, label: 'Create Shares', domain: 'community', description: 'Create shares' },
  { key: PERMISSIONS.COMMUNITY_SHARE_DELETE_OWN, label: 'Delete Own Shares', domain: 'community', description: 'Delete own shares' },
  { key: PERMISSIONS.COMMUNITY_MESSAGE_MANAGE, label: 'Manage Messages', domain: 'community', description: 'Read and write direct messages' },
  { key: PERMISSIONS.COMMUNITY_MESSAGE_READ_OWN, label: 'Read Messages', domain: 'community', description: 'Read own conversation messages' },
  { key: PERMISSIONS.COMMUNITY_MESSAGE_SEND_OWN, label: 'Send Messages', domain: 'community', description: 'Send messages in own conversations' },
  { key: PERMISSIONS.COMMUNITY_MESSAGE_UPDATE_OWN, label: 'Update Own Messages', domain: 'community', description: 'Edit own messages' },
  { key: PERMISSIONS.COMMUNITY_MESSAGE_DELETE_OWN, label: 'Delete Own Messages', domain: 'community', description: 'Delete own messages' },
  { key: PERMISSIONS.COMMUNITY_CONVERSATION_MANAGE, label: 'Manage Conversations', domain: 'community', description: 'Manage own conversations' },
  { key: PERMISSIONS.COMMUNITY_CONVERSATION_READ_OWN, label: 'Read Conversations', domain: 'community', description: 'Read own conversations' },
  { key: PERMISSIONS.COMMUNITY_CONVERSATION_CREATE_OWN, label: 'Create Conversations', domain: 'community', description: 'Create own conversations' },
  { key: PERMISSIONS.COMMUNITY_CONVERSATION_UPDATE_OWN, label: 'Update Own Conversations', domain: 'community', description: 'Update own conversations' },
  { key: PERMISSIONS.COMMUNITY_CONVERSATION_DELETE_OWN, label: 'Delete Own Conversations', domain: 'community', description: 'Delete own conversations' },
  { key: PERMISSIONS.COMMUNITY_CONVERSATION_PARTICIPANT_MANAGE, label: 'Manage Conversation Participants', domain: 'community', description: 'Manage participants in own group conversations' },
  { key: PERMISSIONS.COMMUNITY_AD_MANAGE, label: 'Manage Ads', domain: 'community', description: 'Create and manage ads' },
  { key: PERMISSIONS.COMMUNITY_AD_READ_FEED, label: 'Read Ad Feed', domain: 'community', description: 'Read advertisement feed' },
  { key: PERMISSIONS.COMMUNITY_AD_MANAGE_OWN, label: 'Manage Own Ads', domain: 'community', description: 'Create/update/delete own ads' },
  { key: PERMISSIONS.COMMUNITY_AD_INTERACT, label: 'Interact with Ads', domain: 'community', description: 'Like/comment on ads' },
  { key: PERMISSIONS.COMMUNITY_PUSH_SELF, label: 'Manage Push Tokens', domain: 'community', description: 'Manage own push tokens' },
  { key: PERMISSIONS.COMMUNITY_PUSH_BROADCAST, label: 'Broadcast Push', domain: 'community', description: 'Broadcast push notification to all users' },

  { key: PERMISSIONS.BILLING_PAYMENT_MANAGE_SELF, label: 'Manage Own Payments', domain: 'billing', description: 'Initialize and view own payment records' },
  { key: PERMISSIONS.BILLING_PAYMENT_INITIALIZE_SELF, label: 'Initialize Payment', domain: 'billing', description: 'Initialize own payment transaction' },
  { key: PERMISSIONS.BILLING_PAYMENT_VERIFY_SELF, label: 'Verify Payment', domain: 'billing', description: 'Verify own payment transaction reference' },
  { key: PERMISSIONS.BILLING_PAYMENT_READ_HISTORY_SELF, label: 'Read Payment History', domain: 'billing', description: 'Read own transaction history' },
  { key: PERMISSIONS.BILLING_PAYMENT_READ_DETAIL_SELF, label: 'Read Payment Detail', domain: 'billing', description: 'Read own transaction detail' },
  { key: PERMISSIONS.BILLING_PAYOUT_BANK_VERIFY_SELF, label: 'Verify Payout Bank Account', domain: 'billing', description: 'Verify own payout bank account details' },
  { key: PERMISSIONS.BILLING_PAYOUT_BALANCE_READ_SELF, label: 'Read Payout Balance', domain: 'billing', description: 'Read own provider payout balance and earnings' },
  { key: PERMISSIONS.BILLING_PAYOUT_HISTORY_READ_SELF, label: 'Read Payout History', domain: 'billing', description: 'Read own provider payout history list' },
  { key: PERMISSIONS.BILLING_PAYOUT_DETAIL_READ_SELF, label: 'Read Payout Detail', domain: 'billing', description: 'Read own provider payout details by id' },
  { key: PERMISSIONS.BILLING_PAYOUT_CREATE_SELF, label: 'Create Payout Request', domain: 'billing', description: 'Create own provider payout requests' },
  { key: PERMISSIONS.BILLING_PAYOUT_CANCEL_SELF, label: 'Cancel Payout Request', domain: 'billing', description: 'Cancel own pending provider payout requests' },
  { key: PERMISSIONS.BILLING_PAYOUT_RELEASE_READ_SELF, label: 'Read Payout Releases (Self)', domain: 'billing', description: 'Read own payout release history and release records' },
  { key: PERMISSIONS.BILLING_PAYOUT_PROCESS_ADMIN, label: 'Process Payouts (Admin)', domain: 'billing', description: 'Process provider payouts as admin/internal operator' },
  { key: PERMISSIONS.BILLING_PAYOUT_RELEASE_READ_ADMIN, label: 'Read Payout Releases (Admin)', domain: 'billing', description: 'Read payout release records across providers' },
  { key: PERMISSIONS.BILLING_PAYOUT_RELEASE_CREATE_ADMIN, label: 'Create Payout Releases (Admin)', domain: 'billing', description: 'Create payout release entries tied to source progress' },
  { key: PERMISSIONS.BILLING_SUBSCRIPTION_MANAGE_SELF, label: 'Manage Own Subscriptions', domain: 'billing', description: 'Create and manage own subscriptions' },
  { key: PERMISSIONS.BILLING_SUBSCRIPTION_READ_SELF, label: 'Read Subscriptions', domain: 'billing', description: 'Read own subscriptions' },
  { key: PERMISSIONS.BILLING_SUBSCRIPTION_CREATE_SELF, label: 'Create Subscriptions', domain: 'billing', description: 'Create own subscriptions' },
  { key: PERMISSIONS.BILLING_SUBSCRIPTION_CANCEL_SELF, label: 'Cancel Subscriptions', domain: 'billing', description: 'Cancel own subscriptions' },
  { key: PERMISSIONS.BILLING_PLAN_READ, label: 'Read Plans', domain: 'billing', description: 'Read subscription plans' },
  { key: PERMISSIONS.BILLING_PLAN_MANAGE, label: 'Manage Plans', domain: 'billing', description: 'Create and manage subscription plans' },

  { key: PERMISSIONS.OPS_ANALYTICS_SELF, label: 'Read Self Analytics', domain: 'ops', description: 'Read analytics for own account context' },
  { key: PERMISSIONS.OPS_ADMIN_OVERVIEW_READ, label: 'Read Admin Overview', domain: 'ops', description: 'Read admin overview aggregate metrics' },
  { key: PERMISSIONS.OPS_ADMIN_MAINTENANCE_RECOUNT, label: 'Run Maintenance Recount', domain: 'ops', description: 'Run maintenance recount jobs for denormalized data' },
  { key: PERMISSIONS.OPS_ADMIN_DASHBOARD_STATS_READ, label: 'Read Dashboard Stats', domain: 'ops', description: 'Read global dashboard statistics' },
  { key: PERMISSIONS.OPS_ADMIN_BOOKING_LIST_READ, label: 'Read Booking List (Admin)', domain: 'ops', description: 'Read booking listing in admin moderation' },
  { key: PERMISSIONS.OPS_ADMIN_BOOKING_DETAIL_READ, label: 'Read Booking Detail (Admin)', domain: 'ops', description: 'Read booking detail and related admin context' },
  { key: PERMISSIONS.OPS_ADMIN_BOOKING_STATUS_UPDATE, label: 'Update Booking Status (Admin)', domain: 'ops', description: 'Update booking status as admin moderation action' },
  { key: PERMISSIONS.OPS_ADMIN_BOOKING_FORCE_REFUND, label: 'Force Refund Booking', domain: 'ops', description: 'Force refund a booking and cancel it as admin' },
  { key: PERMISSIONS.OPS_ADMIN_PAYMENT_LIST_READ, label: 'Read Payment List (Admin)', domain: 'ops', description: 'Read transaction list for admin monitoring' },
  { key: PERMISSIONS.OPS_ADMIN_PAYMENT_SUMMARY_READ, label: 'Read Payment Summary (Admin)', domain: 'ops', description: 'Read payment summary aggregates for admin dashboard' },
  { key: PERMISSIONS.OPS_ADMIN_DISPUTE_LIST_READ, label: 'Read Dispute List (Admin)', domain: 'ops', description: 'Read dispute listing for moderation workflow' },
  { key: PERMISSIONS.OPS_ADMIN_DISPUTE_DETAIL_READ, label: 'Read Dispute Detail (Admin)', domain: 'ops', description: 'Read dispute detail and related booking context' },
  { key: PERMISSIONS.OPS_ADMIN_DISPUTE_RESOLVE, label: 'Resolve Disputes (Admin)', domain: 'ops', description: 'Resolve disputes in admin moderation workflow' },
  { key: PERMISSIONS.OPS_ADMIN_SERVICE_MODERATE, label: 'Moderate Services', domain: 'ops', description: 'Activate, deactivate, or delete services as admin' },
  { key: PERMISSIONS.OPS_ADMIN_CONTENT_DELETE, label: 'Delete Content (Admin)', domain: 'ops', description: 'Delete user-generated content as moderation action' },
  { key: PERMISSIONS.OPS_REPORTING_AUDIT_LOG_READ, label: 'Read Audit Logs', domain: 'ops', description: 'Read system audit logs in reporting context' },
  { key: PERMISSIONS.OPS_REPORTING_USER_GROWTH_READ, label: 'Read User Growth Analytics', domain: 'ops', description: 'Read user growth analytics reports' },
  { key: PERMISSIONS.OPS_REPORTING_REVENUE_READ, label: 'Read Revenue Analytics', domain: 'ops', description: 'Read revenue analytics reports' },
  { key: PERMISSIONS.OPS_REPORTING_SERVICE_PERFORMANCE_READ, label: 'Read Service Performance Analytics', domain: 'ops', description: 'Read service performance analytics reports' },
  { key: PERMISSIONS.OPS_REPORTING_CSV_EXPORT, label: 'Export Reporting CSV', domain: 'ops', description: 'Export reporting datasets as CSV' },
  { key: PERMISSIONS.OPS_USER_MANAGEMENT_READ, label: 'Read User Management', domain: 'ops', description: 'Read user and profile data in admin user management' },
  { key: PERMISSIONS.OPS_USER_MANAGEMENT_UPDATE, label: 'Update User Management', domain: 'ops', description: 'Update user core and profile data in admin user management' },
  { key: PERMISSIONS.OPS_USER_STATUS_MANAGE, label: 'Manage User Status', domain: 'ops', description: 'Suspend, ban, or activate users' },
  { key: PERMISSIONS.OPS_USER_VERIFICATION_QUEUE_READ, label: 'Read Verification Queue', domain: 'ops', description: 'Read user verification queue and history' },
  { key: PERMISSIONS.OPS_USER_VERIFICATION_REVIEW, label: 'Review User Verification', domain: 'ops', description: 'Approve or reject verification requests and flags' },
  { key: PERMISSIONS.OPS_USER_STRIKE_MANAGE, label: 'Manage User Strikes', domain: 'ops', description: 'Add, remove, or reset user strikes' },
  { key: PERMISSIONS.OPS_USER_FEATURED_MANAGE, label: 'Manage Featured Users', domain: 'ops', description: 'Toggle featured status for users' },
  { key: PERMISSIONS.OPS_MODERATION_REPORT_CREATE, label: 'Create Moderation Report', domain: 'ops', description: 'Create moderation report for suspicious or inappropriate content' },
  { key: PERMISSIONS.OPS_MODERATION_REPORT_READ, label: 'Read Moderation Reports', domain: 'ops', description: 'Read moderation report queue and report details' },
  { key: PERMISSIONS.OPS_MODERATION_REPORT_RESOLVE, label: 'Resolve Moderation Reports', domain: 'ops', description: 'Resolve moderation reports with status and notes' },
  { key: PERMISSIONS.OPS_PERMISSION_MATRIX_READ, label: 'Read Permission Matrix', domain: 'ops', description: 'Read role and permission matrix data' },
  { key: PERMISSIONS.OPS_PERMISSION_MATRIX_WRITE, label: 'Write Permission Matrix', domain: 'ops', description: 'Assign and update role permission mappings' },
  { key: PERMISSIONS.OPS_USER_ROLE_READ, label: 'Read User Roles', domain: 'ops', description: 'Read assigned roles for users' },
  { key: PERMISSIONS.OPS_USER_ROLE_ASSIGN, label: 'Assign User Roles', domain: 'ops', description: 'Assign/remove/set-primary user roles' },
];
