export enum NotificationType {
  BOOKING_CREATED = 'booking.created',
  BOOKING_CONFIRMED = 'booking.confirmed',
  BOOKING_CHECKOUT_REQUIRED = 'booking.checkout_required',
  BOOKING_STARTED = 'booking.started',
  BOOKING_DELIVERED = 'booking.delivered',
  BOOKING_CORRECTION_REQUESTED = 'booking.correction.requested',
  BOOKING_CANCELLED = 'booking.cancelled',
  BOOKING_DELIVERABLE_UPLOADED = 'booking.deliverable.uploaded',
  BOOKING_DELIVERABLE_SUBMITTED = 'booking.deliverable.submitted',
  BOOKING_DELIVERABLE_APPROVED = 'booking.deliverable.approved',
  BOOKING_DELIVERABLE_REVISION_REQUESTED = 'booking.deliverable.revision_requested',
  BOOKING_MILESTONE_CREATED = 'booking.milestone.created',
  BOOKING_MILESTONE_CONFIRMED = 'booking.milestone.confirmed',
  BOOKING_MILESTONE_SUBMITTED = 'booking.milestone.submitted',
  BOOKING_MILESTONE_APPROVED = 'booking.milestone.approved',
  BOOKING_MILESTONE_REJECTED = 'booking.milestone.rejected',
  BOOKING_COMPLETED = 'booking.completed',
  BOOKING_DISPUTED = 'booking.disputed',
  PAYMENT_INITIATED = 'payment.initiated',
  PAYMENT_COMPLETED = 'payment.completed',
  PAYMENT_FAILED = 'payment.failed',
  PAYOUT_RELEASE_CREATED = 'payout.release.created',
  PAYOUT_RELEASE_FAILED = 'payout.release.failed',
}
